# Site settings
title: Test Supabase Site
description: A Jekyll site with Supabase authentication
baseurl: "/jekyll-supabase-auth"  # Updated so project pages resolve assets/pages
url: "https://nbx0.github.io"

# Build settings
markdown: kramdown
theme: minima

# Sass settings - suppress deprecation warnings from theme
sass:
  quiet_deps: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .git
  - .gitignore
